name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # You can specify the Python version here

      - name: Set up virtual environment
        run: |
            python -m venv venv
            if [[ "$RUNNER_OS" == "Windows" ]]; then
              venv\Scripts\activate
            else
              source venv/bin/activate
            fi
            python -m pip install --upgrade pip
            pip install -r requirements.txt || echo "No requirements.txt found"
  

      - name: Run tests
        run: |
          source venv/bin/activate       # Activate virtual environment again
          python -m unittest discover
